# Site settings
title: Yosuke TOMITA
tag_text: Yosuke TOMITA
description: 日本の東京都で活動している ふりかえりコーチ, 教育DXプロデューサー です. 元システムコンサルタント, ソフトウェアエンジニア，役者．

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
